apo-npt.mdp:
  title: 
  integrator: md
  nsteps: '50000'
  dt: '0.002'
  nstxout: '500'
  nstvout: '500'
  nstenergy: '500'
  nstlog: '500'
  continuation: 'yes'
  constraint_algorithm: lincs
  constraints: h-bonds
  lincs_iter: '1'
  lincs_order: '4'
  cutoff-scheme: Verlet
  ns_type: grid
  nstlist: '10'
  rcoulomb: '1.0'
  rvdw: '1.0'
  DispCorr: EnerPres
  coulombtype: PME
  pme_order: '4'
  fourierspacing: '0.16'
  tcoupl: V-rescale
  tc-grps: System
  tau_t: 0.1
  ref_t: 309.65 
  pcoupl: Parrinello-Rahman
  pcoupltype: isotropic
  tau_p: '2.0'
  ref_p: '1.01325'
  compressibility: '4.5e-5'
  refcoord_scaling: com
  pbc: xyz
  gen_vel: 'no'
apo-ions.mdp:
  include: ''
  define: ''
  integrator: steep
  tinit: '0'
  dt: '0.001'
  nsteps: '-1'
  init-step: '0'
  simulation-part: '1'
  comm-mode: Linear
  nstcomm: '1000'
  comm-grps: ''
  bd-fric: '0'
  ld-seed: '-1'
  emtol: '1'
  emstep: '0.001'
  niter: '20'
  fcstep: '1'
  nstcgsteep: '10000000'
  nbfgscorr: '10'
  rtpi: '0.05'
  nstxout: '1000'
  nstvout: '1000'
  nstfout: '1000'
  nstlog: '1000'
  nstcalcenergy: '1000'
  nstenergy: '1000'
  nstxout-compressed: '1000'
  compressed-x-precision: '1000'
  compressed-x-grps: ''
  cutoff-scheme: Verlet
  nstlist: '30'
  pbc: xyz
  periodic-molecules: 'yes'
  verlet-buffer-tolerance: '0.005'
  rlist: '1.2'
  coulombtype: PME
  coulomb-modifier: ''
  rcoulomb-switch: '0'
  rcoulomb: '1.5'
  epsilon-r: '1'
  epsilon-rf: '0'
  vdw-type: PME
  vdw-modifier: none
  rvdw-switch: '0'
  rvdw: '1.5'
  DispCorr: EnerPres
  table-extension: '1'
  energygrp-table: ''
  fourierspacing: ''
  fourier-nx: ''
  fourier-ny: ''
  fourier-nz: ''
  pme-order: '8'
  ewald-rtol: 1e-05
  ewald-rtol-lj: '0.001'
  lj-pme-comb-rule: Geometric
  ewald-geometry: 3d
  epsilon-surface: '0'
  constraints: none
  constraint-algorithm: Lincs
  continuation: 'no'
  Shake-SOR: 'no'
  shake-tol: '0.0001'
  lincs-order: '4'
  lincs-iter: '3'
  lincs-warnangle: '30'
  morse: 'no'
  energygrp-excl: ''
apo-sdm.mdp:
  title:
  integrator: md
  nsteps: '250000000'
  dt: '0.002'
  nstxout: '5000'
  nstvout: '5000'
  nstfout: '5000'
  nstenergy: '5000'
  nstlog: '5000'
  nstxout-compressed: '5000'
  compressed-x-grps: System
  continuation: 'yes'
  constraint_algorithm: lincs
  constraints: h-bonds
  lincs_iter: '1'
  lincs_order: '4'
  cutoff-scheme: Verlet
  ns_type: grid
  nstlist: '10'
  rcoulomb: '1.0'
  rvdw: '1.0'
  coulombtype: PME
  pme_order: '4'
  fourierspacing: '0.16'
  tcoupl: V-rescale
  tc-grps: System
  tau_t: 0.1
  ref_t: 309.65 
  pcoupl: Parrinello-Rahman
  pcoupltype: isotropic
  tau_p: '2.0'
  ref_p: '1.01325'
  compressibility: '4.5e-5'
  pbc: xyz
  DispCorr: EnerPres
  gen_vel: 'no'
apo-min-cg.mdp:
  include: ''
  define: -DPOSRES -DFLEXIBLE
  integrator: cg
  tinit: '0'
  dt: '0.0001'
  nsteps: '-1'
  init-step: '0'
  simulation-part: '1'
  comm-mode: Linear
  nstcomm: '1000'
  comm-grps: ''
  bd-fric: '0'
  ld-seed: '-1'
  emtol: '100.0'
  emstep: '0.001'
  nstcgsteep: '10'
  nbfgscorr: '10'
  niter: '20'
  fcstep: '0'
  rtpi: '0.05'
  nstxout: '1000'
  nstvout: '1000'
  nstfout: '10'
  nstlog: '1000'
  nstcalcenergy: '1000'
  nstenergy: '1000'
  nstxout-compressed: '1000'
  compressed-x-precision: '1000'
  compressed-x-grps: ''
  cutoff-scheme: Verlet
  nstlist: '30'
  pbc: xyz
  periodic-molecules: 'yes'
  verlet-buffer-tolerance: '0.01'
  rlist: '1.3'
  coulombtype: PME
  coulomb-modifier: ''
  rcoulomb-switch: '0'
  rcoulomb: '1.5'
  epsilon-r: '1'
  epsilon-rf: '0'
  vdw-type: PME
  vdw-modifier: none
  rvdw-switch: '0'
  rvdw: '1.5'
  DispCorr: EnerPres
  table-extension: '1'
  energygrp-table: ''
  fourierspacing: ''
  fourier-nx: ''
  fourier-ny: ''
  fourier-nz: ''
  pme-order: '6'
  ewald-rtol: 1e-05
  ewald-rtol-lj: '0.001'
  lj-pme-comb-rule: Geometric
  ewald-geometry: 3d
  epsilon-surface: '0'
  implicit-solvent: 'No'
  tcoupl: 'No'
  nsttcouple: '-1'
  nh-chain-length: '10'
  print-nose-hoover-chain-variables: 'no'
  tau-t: ''
  ref-t: ''
  pcoupl: 'No'
  pcoupltype: Isotropic
  nstpcouple: '-1'
  tau-p: '1'
  compressibility: ''
  ref-p: ''
  refcoord-scaling: 'No'
  annealing: ''
  annealing-npoints: ''
  annealing-time: ''
  annealing-temp: ''
  gen-vel: 'no'
  gen-temp: '300'
  gen-seed: '-1'
  constraints: none
  constraint-algorithm: Lincs
  continuation: 'no'
  Shake-SOR: 'no'
  shake-tol: '0.0001'
  lincs-order: '4'
  lincs-iter: '1'
  lincs-warnangle: '30'
  morse: 'no'
  energygrp-excl: ''
  nwall: '0'
  wall-type: 9-3
  wall-r-linpot: '-1'
  wall-atomtype: ''
  wall-density: ''
  wall-ewald-zfac: '3'
  pull: 'no'
  rotation: 'no'
  IMD-group: ''
  disre: Simple
  disre-weighting: Conservative
  disre-mixed: 'no'
  disre-fc: '1000'
  disre-tau: '0'
  nstdisreout: '0'
  orire: 'no'
  orire-fc: '0'
  orire-tau: '0'
  orire-fitgrp: ''
  nstorireout: '100'
  free-energy: 'no'
  couple-moltype: ''
  couple-lambda0: vdw-q
  couple-lambda1: vdw-q
  couple-intramol: 'no'
  init-lambda: '-1'
  init-lambda-state: '-1'
  delta-lambda: '0'
  nstdhdl: '50'
  fep-lambdas: ''
  mass-lambdas: ''
  coul-lambdas: ''
  vdw-lambdas: ''
  bonded-lambdas: ''
  restraint-lambdas: ''
  temperature-lambdas: ''
  calc-lambda-neighbors: '1'
  init-lambda-weights: ''
  dhdl-print-energy: 'no'
  sc-alpha: '0'
  sc-power: '1'
  sc-r-power: '6'
  sc-sigma: '0.3'
  sc-coul: 'no'
  separate-dhdl-file: 'yes'
  dhdl-derivatives: 'yes'
  dh_hist_size: '0'
  dh_hist_spacing: '0.1'
  acc-grps: ''
  accelerate: ''
  freezegrps: ''
  freezedim: ''
  cos-acceleration: '0'
  deform: ''
  simulated-tempering: 'no'
  simulated-tempering-scaling: geometric
  sim-temp-low: '300'
  sim-temp-high: '300'
  E-x: ''
  E-xt: ''
  E-y: ''
  E-yt: ''
  E-z: ''
  E-zt: ''
  swapcoords: 'no'
  adress: 'no'
apo-min-steep.mdp:
  include: ''
  define: -DPOSRES -DFLEXIBLE
  integrator: steep
  tinit: '0'
  dt: '0.001'
  nsteps: '-1'
  init-step: '0'
  simulation-part: '1'
  comm-mode: Linear
  nstcomm: '1000'
  comm-grps: ''
  bd-fric: '0'
  ld-seed: '-1'
  emtol: '100'
  emstep: '0.001'
  niter: '20'
  fcstep: '1'
  nstcgsteep: '10'
  nbfgscorr: '10'
  rtpi: '0.05'
  nstxout: '1000'
  nstvout: '1000'
  nstfout: '1000'
  nstlog: '1000'
  nstcalcenergy: '1000'
  nstenergy: '1000'
  nstxout-compressed: '1000'
  compressed-x-precision: '1000'
  compressed-x-grps: ''
  cutoff-scheme: Verlet
  nstlist: '30'
  pbc: xyz
  periodic-molecules: 'yes'
  verlet-buffer-tolerance: '0.005'
  rlist: '1.2'
  coulombtype: PME
  coulomb-modifier: ''
  rcoulomb-switch: '0'
  rcoulomb: '1.5'
  epsilon-r: '1'
  epsilon-rf: '0'
  vdw-type: PME
  vdw-modifier: none
  rvdw-switch: '0'
  rvdw: '1.5'
  DispCorr: EnerPres
  table-extension: '1'
  energygrp-table: ''
  fourierspacing: ''
  fourier-nx: ''
  fourier-ny: ''
  fourier-nz: ''
  pme-order: '8'
  ewald-rtol: 1e-05
  ewald-rtol-lj: '0.001'
  lj-pme-comb-rule: Geometric
  ewald-geometry: 3d
  epsilon-surface: '0'
  constraints: none
  constraint-algorithm: Lincs
  continuation: 'no'
  Shake-SOR: 'no'
  shake-tol: '0.0001'
  lincs-order: '4'
  lincs-iter: '3'
  lincs-warnangle: '30'
  morse: 'no'
  energygrp-excl: ''
apo-nvt.mdp:
  title:
  define: -DPOSRES
  integrator: md
  nsteps: '50000'
  dt: '0.002'
  nstxout: '2500'
  nstvout: '2500'
  nstenergy: '2500'
  nstlog: '2500'
  continuation: 'no'
  constraint_algorithm: lincs
  constraints: h-bonds
  lincs_iter: '1'
  lincs_order: '4'
  cutoff-scheme: Verlet
  ns_type: grid
  nstlist: '10'
  rvdw: '1.2'
  rvdw-switch: '1.0'
  vdw-modifier: force-switch
  DispCorr: 'No'
  rcoulomb: '1.2'
  coulombtype: PME
  pme_order: '4'
  fourierspacing: '0.16'
  tcoupl: V-rescale
  tc-grps: System
  tau_t: '1.0'
  ref_t: '298'
  pcoupl: 'no'
  pbc: xyz
  gen_vel: 'yes'
  gen_temp: '298'
  gen_seed: '-1'
