recycling_steps: 10
sampling_steps: 200
diffusion_samples: 50
max_parallel_samples: 6
step_scale: 1.638
max_msa_seqs: 8192
num_subsampled_msa: 1024
num_workers: 8
preprocessing_threads: 16
use_msa_server: true
msa_pairing_strategy: complete
subsample_msa: true
use_potentials: true
output_format: mmcif
write_full_pae: true
write_full_pde: true
no_kernels: true
override: true
